apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apworld-cert
spec:
  secretName: apworld-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - apworld.siluni.fr