apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: images
  namespace: acpl-forum

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: ""

  resources:
    requests:
      storage: 1Ti