apiVersion: v1
kind: Secret
metadata:
    name: forum-secret
type: Opaque
stringData:
    DEFAULT_URI: ENC[AES256_GCM,data:yAEVzrd0dG2cNR1hrhfU7Yug8MHowUJYhQ==,iv:htZthEgPZgB4UPn+IZaiVAQzIwUlx4BlU+NFjiRTlDI=,tag:s6fX2/3ZygmYXfmIagOVGw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:K0Gg76FWMsKYOluM1eqiKJMWCLaIXAc79eY2jBn390S4iES1MQvgmJfgc5JMJOFXXRLUQZAe7S+IoBq1a2R00J0pEbe48LNCAxcTvmQp/Ixod/ygjKCbJ0KL7QrD5Hw=,iv:Wb435MxjTd7QsuTqebTRE2G2UTITSeAbSCsA1mFgklM=,tag:9wNnCAw741yHykmcwVLssA==,type:str]
    GITHUB_API_TOKEN: ENC[AES256_GCM,data:cY+w6mF4ykNdlVLYZyK/lnQTKa62rAJf3HayaqXiuNGb+i0EtrIv1gBa7yBtjm76zeTnzFxPQd3pAJAc1QQwkGgTWia+/3y3YWgJ4ZrqdMxVTE9qPGr3BnvAstPW,iv:H7i9gy4/YDPFaZM1239IfFNzYiYm4WJqTnXu1oPUTss=,tag:BSkiKjO7DUB7syyFn7LN1g==,type:str]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:MrjVeWD5N6B7hZPLYDVgTC5/DqWQpJqjxeL/GMDU,iv:1iaPq3ZRgvGHCXwq0kE6NTZHNNuAtHH/vscGt6HiPjY=,tag:V77WwcTsYG9amaG0tC9HvA==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:ttwgE3U41rgp07dQBnE6RriKx7/5No+4DgazXqfj,iv:ebwbwEB80+s9gZPipGCm5arWSkZQDySRzIK4/QQnYQo=,tag:rUr37hX6cLYA5Pv2VbIykA==,type:str]
    OAUTH_DISCORD_CLIENT_ID: ENC[AES256_GCM,data:cBBcuNLmbRGckuEtrKVE9hV31A==,iv:a2tO5JehrdUNOzK/qAGLy86qgNgVW4yM2SFw/qxeKgU=,tag:9qwKZ/PXLlbQ3uJUDB88Tg==,type:str]
    OAUTH_DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:BOfQrgbGpElTamUaIwaUHRNKuJPrU5EBQC546KKwCh4=,iv:JThD2xSdk/FEBndc9n307B7gMnsqI+hcgV5SPmb9S2s=,tag:PkmO4N6pNxrS4tKnYe0rAw==,type:str]
    SERVER_NAME: ENC[AES256_GCM,data:bK6F,iv:2Icn2vwHv6I0MfdP+2Gze15abGDxlDN2ZuEProZgLlk=,tag:CjEh6hSnCHopSoaX5pif4Q==,type:str]
    YOUTUBE_API_KEY: ENC[AES256_GCM,data:zMhX7VYc2vum9y48EBZhTwS8Z7oGCCKaw8JXff/NczjHFgTbnQye,iv:N0yX18PoVAYT/6rItJ38lL7GbEG/cCUWr2Ip5qShwwY=,tag:gfgrEanBHfb9TCTDj1dX9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNEloK3duclM2N296dDN6
            allIWjk3T2FoZnNSRklxek9FeDlKUjZPWUdJCndrcWV2M3c2T2p1ckEwRFoydTND
            bHpHa1hNeFdDY09KTnpNTjQxaHVGRmcKLS0tIEhNV1VKSkFKcm5YTUZpWVFlVDRO
            cjZiaTh5SU1HRHdPdlJLS1pLeTRETEUKtPgDVib8Nr0rc47qUhWGYedrYjDd525j
            j8gNp+hK0mYUHzJCd8nBxaxiPt2tIT1ZT/6Atjt8fbVQSG6haWRWbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1puesr5alxtmnn7lsf94az9t4cmk577z9pklvrse3mgkrneg8zaqquthqh8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T16:47:00Z"
    mac: ENC[AES256_GCM,data:I5Kp2K+dU81EpnQcoWB2mzZwjN/agmUUijx0/r7gx8LtKnaQPR8r17X8QL9HW9w13FxcKYn2CSngczgBUPS/7nlpzXUuNd2hg/jDOAcohaf7FalBUPVw8/IPZkCgJwq3vI8wDlAlB5fHDZMQX1kzCil+4tVTnuBoVE1x/il7LCo=,iv:6j+4t667SbYFA4Nw8g5qd75Qe8Zq0Oxn2byYSLjTpmw=,tag:cI6QjTjT2yseFOB/Px0VpA==,type:str]
    version: 3.13.1
