apiVersion: v1
kind: Secret
metadata:
    name: runner-secret
type: Opaque
stringData:
    ACCESS_TOKEN: ENC[AES256_GCM,data:NojM4g8De3ZX1LSPrJ+zFONlzKNV5HdVKaTB6vBN/VAHHn0oJE/voTycFEM7DP9jku0p86wBQrbLh+oKI0WtAMQD/Nhdacen4gYHIhd37IRTrbEqYPWyejwp1S8/,iv:NFz2AJoTVKsApkAXQz0IR80LzWRl4PiQVR06XbuDaYY=,tag:KqRbO3HZR6JfMGzPWWDbDQ==,type:str]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRlZRbEhSbUxxbFBXTG5o
              d1g5TGtsenIzY2FlZDEwb01IYkMvZVNzazAwCnhzTUVGNG1WdWtLSWlCaStxQkdp
              VlNtWUF4alNDY2RkRzJ0RHNCTjlndWcKLS0tIFJpL0tYeWcwbkp0aE9La2pnVmRK
              WVEzUFhYQitsalpsOXdWeXdhK0kyVUEKbW/sKLEnAXkpORYgus8T+/iAfz+FNW8j
              50dDc+pGrvDGLrkDJVIu0W4YKZSfZfGr5mFw+H0WGNFFwAEYO88Wfg==
              -----END AGE ENCRYPTED FILE-----
          recipient: age1puesr5alxtmnn7lsf94az9t4cmk577z9pklvrse3mgkrneg8zaqquthqh8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T15:49:39Z"
    mac: ENC[AES256_GCM,data:ZHN8qHMyv4VHbsPYqINzGqk/EUTsfinp+88KJhxwvADQie/fdaKvHKr2OIvYRRSiAJi627tL6wHpSLdIKc/ye2WhONSyUepcpS0qGPcLSuT0kli0vj/8jNa7AgZ32o3h+V0s9EIrIUGoSovNdZb3Kjo7oFIE/PRFqLjy3qb0BqA=,iv:3tcHZKKhS+AFtoJeqzuhinqJSbcTWzwqsbQYq+L/HU4=,tag:KKMdkHNf2725LXTE44t2Og==,type:str]
    version: 3.13.1
