apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: images

data:
  default.conf: |
    server {
      listen 80;

      root /images;

      location / {
        autoindex off;
        try_files $uri =404;

        sendfile on;
        tcp_nopush on;

        open_file_cache max=100000 inactive=60s;
        open_file_cache_valid 120s;
        open_file_cache_min_uses 2;

        etag on;
        expires 365d;
        add_header Cache-Control "public, immutable";
      }
    }