apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images
  namespace: images
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  volumeName: images-pv
  resources:
    requests:
      storage: 1Ti
